### ISSUE TITLE
No test is available for NUnit

### ISSUE THREAD

**Issue by oakio** [JetBrains/TeamCity.VSTest.TestAdapter#10]
Command `dotnet test` executed with message "No test is available in C:\temp\MyApp\build\bin\net461\MyApp.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again." 

My configuration:
```
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.8.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0-preview-20170923-02" />
    <PackageReference Include="TeamCity.VSTest.TestAdapter" Version="1.0.5" />
  </ItemGroup>
```
But when `TeamCity.VSTest.TestAdapter` package removed, all tests were successful found.

**Comment by dtretyakov** [comment]
@oakio, could you please report version of TeamCity .NET CLI plugin?

**Comment by oakio** [comment]
How to detect plugin version? All "Bundled plugins" in our Teamcity has version 47070.

**Comment by dtretyakov** [comment]
@oakio, do you use to execute `dotnet test` [TeamCity .NET CLI plugin](https://plugins.jetbrains.com/plugin/9190--net-cli-support) or run it via command line runner?

**Comment by oakio** [comment]
Via command line (powershell script aka build script).

**Comment by NikolayPianikov** [comment]
@oakio is it possible to share simple solution to reproduce? Did you manually change the output directory?

**Comment by oakio** [comment]
https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/pull/11

**Comment by NikolayPianikov** [comment]
Released [here](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/releases/tag/1.0.6)
