### ISSUE TITLE
Tests not reported with xunit

### ISSUE THREAD

**Issue by zone117x** [JetBrains/TeamCity.VSTest.TestAdapter#19]
Followed exact instructions. MSTest is being reported but xunit tests are not. Using netcoreapp2.0 and Ubuntu build agent. 
Tried with the dotnet core CLI runner with `dotnet test` and `dotnet vstest`, and tried custom script with both as well.

**Comment by NikolayPianikov** [comment]
Source of the problem: https://github.com/Microsoft/vstest/issues/1590
