### ISSUE TITLE
TeamCity.VSTest.TestLogger.dll not included after dotnet publish

### ISSUE THREAD

**Issue by mexisd** [JetBrains/TeamCity.VSTest.TestAdapter#21]
.NetCoreCli: v2.1.202

Given a .NetCore project that references 
```
<PackageReference Include="TeamCity.VSTest.TestAdapter" Version="1.0.10" />
```
after `dotnet publish {projectName}.csproj`, the assembly `TeamCity.VSTest.TestLogger.dll` is not included in the published artifacts.

As a result if I use `dotnet vstest {projectName}.dll` to run my tests from TeamCity, no report is added. TeamCity will just report `Success` which is not very useful, instead of `Tests passed: {numberOfTests}`.

If I copy the file manually to the output before running my tests I get the correct results on TeamCity.

Am I doing something wrong? To me it seems that file should be included.

**Comment by mhail** [comment]
After digging through TeamCity.VSTest.TestAdapter.props the file is only copied when IsUnderTeamCity is set to true this can be faked from the dotnet command line using ```-p:IsUnderTeamCity=true``` or adding a property definition to the project file.

Ex: command line is ```dotnet test``` ... ```--test-adapter-path:. --logger:TeamCity -p:IsUnderTeamCity=true```

**Comment by NikolayPianikov** [comment]
@mexisd To run tests using this adapter you should use the dotnet CLI command `dotnet test` to run tests for a project or a solution not for an assembly. In this case dotnet CLI runs `restore`, `build` and `vstest` targets.

To run tests for specific testing assembly you should use the 'dotnet vstest' command.

**Comment by NikolayPianikov** [comment]
@mhail  There are no any reasons to use `IsUnderTeamCity` under a TeamCity agent process because of this property is always true for this case.

```xml
<IsUnderTeamCity Condition=" '$(TEAMCITY_PROJECT_NAME)' != '' or '$(TEAMCITY_VERSION)' != '' ">true</IsUnderTeamCity>
```

TeamCity agent process always has environment variables `TEAMCITY_PROJECT_NAME` and `TEAMCITY_VERSION`.

**Comment by mexisd** [comment]
@mhail @NikolayPianikov Thanks for your responses. I will try the `-p:IsUnderTeamCity=true` and come back to you.

I am using the `dotnet vstest` but because the `TeamCity.VSTest.TestLogger.dll` is not in the artifacts I don't get results on TeamCity. For now I added the `DLL` manually and the reporting works. 

I would expect when I do the `dotnet publish` to have the `DLL` in the artifacts. Is that assumption wrong?

Essentially, these are post deployment tests. I don't want to re-compile the whole project. So, in the build process of the application under test, a `functional-tests.zip` folder will be created with the outcome of the `dotnet publish` for the functional tests project. There the `TeamCity.VSTest.TestLogger.dll` is missing. Later another TC agent will download the artifacts through `Artifact Dependency` and run the `dotnet vstest` command. 

As I mentioned no results will be recorded. After adding the file in the artifacts I get results. If I use the `dotnet test {projectName}.csproj` I get correct results. But I don't want to re-build and want to use the existing artifacts.

**Comment by NikolayPianikov** [comment]
@mexisd Are you using the [dotnet CLI plugin](https://github.com/JetBrains/teamcity-dotnet-plugin) to run `dotnet vstest` command?

**Comment by mexisd** [comment]
@NikolayPianikov Good question. To not have a dependency on a specific agent the `CLI`, for the version we want, gets downloaded locally, during the build and that's the one being used.

**Comment by NikolayPianikov** [comment]
@mexisd From the TeamCity command line runner you could run tests like:
`dotnet vstest tests.dll /Logger:teamcity /TestAdapterPath:%teamcity.tool.TeamCity.Dotnet.Integration.DEFAULT%/vstest15`

**Comment by NikolayPianikov** [comment]
@mexisd if you have any questions feel free to reopen it
