### ISSUE TITLE
Building with .NET Core SDK 2.2.200 fails with Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'logger://teamcity/'

### ISSUE THREAD

**Issue by flcdrg** [JetBrains/TeamCity.VSTest.TestAdapter#31]
.NET Core SDK 2.2.200 (which is included in Visual Studio 2019) changes how MSBuildToolsVersion is defined.

This presumably means that https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/blob/master/TeamCity.VSTest.TestLogger/TeamCity.VSTest.TestAdapter.props needs updating to match the new Current value

**Comment by flcdrg** [comment]
This probably is more generally a requirement to support Visual Studio 2019

**Comment by flcdrg** [comment]
Presumably .NET Core SDK 2.1.600 will also be affected

**Comment by danpowell88** [comment]
Just saw there was a commit to fix this, any idea when the nuget package will get released?

**Comment by NikolayPianikov** [comment]
@danpowell88 I hope today

**Comment by NikolayPianikov** [comment]
The package was uploaded to nuget.org as 1.0.15

**Comment by flcdrg** [comment]
This is still broken

**Comment by danpowell88** [comment]
The fix worked for me

**Comment by flcdrg** [comment]
Apologies.. Turns out I'd upgraded to 1.0.14, not 15 :-(

**Comment by jfloodnet** [comment]
The issue affects running dotnet test in docker builds using microsoft/dotnet:2.1-sdk (as @flcdrg mentions it [here](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/issues/31#issuecomment-469097015)
