### ISSUE TITLE
support for .net core 3

### ISSUE THREAD

**Issue by elitastic** [JetBrains/TeamCity.VSTest.TestAdapter#34]
Could you please add support for .net core 3?

When I use ".net core 3.0.0-preview8" to build I have the same issue like described in https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/issues/31:

`Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'teamcity'`

**Comment by NikolayPianikov** [comment]
@elitastic could you add a sample to reproduce?
Also could you run `dotnet --info`

**Comment by elitastic** [comment]
See below the output from dotnet --info.

I think it needs the same fix as you created to support vs 2019 https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/commit/9e25b799623f6a67c48f309d6b83f2364d06bd01 but this time for MSBuildToolsVersion 16 instead of 15:


Looks like the problem is that "TeamCity.VSTest.TestLogger.dll" is not copied to output, when building with msbuild from .net core 3.

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by NikolayPianikov** [comment]
@elitastic I cannot reproduce this issue. Looks `TeamCity.VSTest.TestAdapter.props` contains correct logic for the case when '$(MSBuildToolsVersion)' == '16.0'. Try the following script to check it:

```
md sample
pushd sample
dotnet new mstest
dotnet add package TeamCity.VSTest.TestAdapter
SET TEAMCITY_VERSION=2019.2
dotnet test
popd
rd sample /S /Q
```

You will TeamCity service messages like `##teamcity[`

**Comment by elitastic** [comment]
You're right, it works when you set the TEAMCITY_VERSION environment variable before building the project. Teamcity is not installed on my local machine that's why it didn't work. Please note that it works without setting TEAMCITY_VERSION environment when building with .net core < 3.0.

**Comment by NikolayPianikov** [comment]
it should not produce TeamCity service messages when it is not running under TeamCity. When we are specifying `SET TEAMCITY_VERSION=2019.2` we just emulate a running under TeamCity 

I've tried the following script for dotnet core 2.2.401 and it does not produce service messages if we does not set `TEAMCITY_VERSION`:

```
md sample
pushd sample
dotnet new globaljson --sdk-version 2.2.401
dotnet new mstest
dotnet add package TeamCity.VSTest.TestAdapter
rem SET TEAMCITY_VERSION=2019.2
dotnet test
popd
rd sample /S /Q
```

**Comment by NikolayPianikov** [comment]
@elitastic Could you provide some script to reproduce your issue?

**Comment by elitastic** [comment]
`dotnet test --logger:teamcity`

This command fails when building with dotnet >= 3.0 but works with dotnet < 3.0 even when not running on teamcity. But it's fine for me, I changed my gulp script that it only specifies --logger:teamcity when running on teamcity.

**Comment by NikolayPianikov** [comment]
I am not sure it is possible

**Comment by AnSmol** [comment]
> @elitastic I cannot reproduce this issue. Looks like `TeamCity.VSTest.TestAdapter.props` contains correct logic for the case when '$(MSBuildToolsVersion)' == '16.0'. Try the following script to check it:
> 
> ```
> md sample
> pushd sample
> dotnet new mstest
> dotnet add package TeamCity.VSTest.TestAdapter
> SET TEAMCITY_VERSION=2019.2
> dotnet test
> popd
> rd sample /S /Q
> ```
> 
> You will see TeamCity service messages like `##teamcity[`

`Dotnet test` and `Dotnet vstest /path/to/file.dll /Logger:teamcity /TestAdapterPath:.` both work with  dotnet 3.0.100. 
But please replace gif on the README.md to metioned commands snippet. Spent 40 minutes to figure out that example does not work because of absence TEAMCITY_VERSION envinronmet variable.

**Comment by NikolayPianikov** [comment]
@antonarhipov I've added notes under the demo video.
