### ISSUE TITLE
FlowId is a sequential number instead of the intended GUID

### ISSUE THREAD

**Issue by batzen** [JetBrains/TeamCity.VSTest.TestAdapter#38]
The FlowId emitted is not generated by the included `FlowIdGenerator` as the IOC registration uses the default parameter-less constructor of `TeamCityServiceMessages`.
I could create a PR to fix this if someone could help me with the correct way to add tests for this.

**Comment by NikolayPianikov** [comment]
@batzen thx for reporting. I've published 1.0.22, it contains fix.

**Comment by batzen** [comment]
Thanks a lot. 👍
