### ISSUE TITLE
.net 5 support

### ISSUE THREAD

**Issue by bill-robbins-ss** [JetBrains/TeamCity.VSTest.TestAdapter#42]
This package does not copy `TeamCity.VSTest.TestAdapter.dll` and `TeamCity.VSTest.TestLogger.dll` when the project is using `net5.0`. 

Note that `IoC.dll` and `TeamCity.ServiceMessages.dll` _are_ copied. 

As a workaround, I extracted the two files and added them to my project in `dependencies\` then copy them using MSBuild. 

```
  <ItemGroup>
    <DependencyFiles Include="$(ProjectDir)\dependencies\*.dll"/>
  </ItemGroup>

  <Target Name="CopyDependencies" BeforeTargets="PreBuildEvent">
    <Copy
        SourceFiles="@(DependencyFiles)"
        DestinationFolder="$(TargetDir)"/>
  </Target>
```

**Comment by NikolayPianikov** [comment]
@bill-robbins-ss how did you create your test project. I am trying to reproduce:
```
md tests
pushd tests
dotnet new globaljson --sdk-version 5.0
dotnet new xunit
dotnet add package TeamCity.VSTest.TestAdapter
set TEAMCITY_PROJECT_NAME=Tests
dotnet test
popd
```

**Comment by bill-robbins-ss** [comment]
🤔 I didn't RTFM enough. There is a handful of indirection between my project's tests in docker-compose and TeamCity running them, so I was not passing through all of those environment variables. 

```
dotnet test -l teamcity
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'teamcity'.
```
