### ISSUE TITLE
Not working on .NET 7

### ISSUE THREAD

**Issue by patafx** [JetBrains/TeamCity.VSTest.TestAdapter#45]
Hi,

The adaptater is not working since I migrated CI to .NET 7.

My configuration :
TeamCity 2022.10.1 (build 116934)
Visual Studio 17.4.2
Dotnet 7.0.100

**Comment by mchechulnikov** [comment]
Hi @patafx 

If please check [this comment](https://github.com/JetBrains/teamcity-dotnet-plugin/issues/159#issuecomment-1321937091). Could it help?

**Comment by mchechulnikov** [comment]
@patafx does it work for you?

**Comment by patafx** [comment]
Yes of course.
