### ISSUE TITLE
Adapter isn't compatible with .NET Core 2.0

### ISSUE THREAD

**Issue by bording** [JetBrains/TeamCity.VSTest.TestAdapter#5]
I've been working on moving projects to .NET Core 2.0, using the Visual Studio 2017 15.3 preview release to do it. 

As part of adjusting our build configuration, I've been getting tests running on .NET Core via `dotnet test`, and I was excited to come across this package because not having test integration has definitely been a bit painful.

However, this package does not work with `dotnet test` for .NET Core 2.0. It turns out Microsoft is changing how test loggers are discovered. Instead of looking for an assembly named `*.testadapter.dll`, they are now looking for `*.testlogger.dll` instead:

https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#naming

I was able to verify that this change got the logger working properly by building a local copy of this repo, with the assembly name changed to TeamCity.VSTest.TestLogger.dll. 

Given that .NET Core 2.0 is still in preview, would it be possible to release a prerelease version of this package that includes this change?

**Comment by NikolayPianikov** [comment]
@bording yes I think it is possible, I will check a compatibility

**Comment by bording** [comment]
@NikolayPianikov Any progress on this? Since .NET Core 2.0 was released today, it would be nice to have a test adapter that works with it.

**Comment by gulbanana** [comment]
Yes, please! I have a lot of teamcity builds in which I'd like to start using 2.0.

**Comment by NikolayPianikov** [comment]
I've fixed and published v1.0.1
