### ISSUE TITLE
NUnit3TestAdapter 3.8.0

### ISSUE THREAD

**Issue by ecourtenay** [JetBrains/TeamCity.VSTest.TestAdapter#6]
It appears that TeamCity.VSTest.TestAdapter isn't compatible with NUnit3TestAdapter - is this a known issue?

**Comment by NikolayPianikov** [comment]
Look like it could be an issue. Is it possible to create simple project to reproduce? My 
[sample](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/files/1223362/a.zip) works fine

**Comment by NikolayPianikov** [comment]
@ecourtenay do you still have this issue?

**Comment by NikolayPianikov** [comment]
@ecourtenay I can't reproduce this issue. I've closed this issue, but please feel free to reopen it again if it still actual.
