### ISSUE TITLE
Update Wiki to include details about teamcity detection

### ISSUE THREAD

**Issue by drewfreyling** [JetBrains/TeamCity.VSTest.TestAdapter#8]
I'm currently running my net core tests inside a docker container from my teamcity server. By doing this I don't get the tests results reporting to teamcity. I'm wondering if it is worth mentioning in the wiki that the test adapter looks for the `TEAMCITY_PROJECT_NAME` environment variable to know if it needs to send the text messages to the team city server? This would have saved me a fair bit of time so hoping it helps someone else.

Happy to update the wiki if this is considered a good idea...

**Comment by NikolayPianikov** [comment]
@drewfreyling We will be very grateful if you do this. thank you in advance

**Comment by NikolayPianikov** [comment]
@drewfreyling unfortunately I have no required access rights to add you as repo writer, so if you faced any issues to change a wiki, I could help and add your paragraph/wiki page

**Comment by NikolayPianikov** [comment]
@drewfreyling also may be there is some way to define that logger works inside a docker container (env vars or so on)

**Comment by drewfreyling** [comment]
I will need someone to add it in as I don't have access to change the wiki.

I'm thinking of adding a simple statement under the paragragh "Note that this package does not impact tests run locally, but only those run under TeamCity." which reads:

> The TeamCity.VSTest.TestAdapter package looks for the environment variable `TEAMCITY_PROJECT_NAME` to know whether it is running in a TeamCity environment and that it needs to send the text messages to the TeamCity server.

**Comment by NikolayPianikov** [comment]
@drewfreyling I've added a new part to the Wiki home page "Important notes" and your notes (with a cosmetic change). Thank you

**Comment by NikolayPianikov** [comment]
@drewfreyling Could you close this issue if everything is correct?
